package com.jimmie.domain.creatures;

public enum CreatureConditionType {
	NONE, BLINDED, DAZED, DEAFENED, DOMINATED, DYING, HELPLESS,
	IMMOBILIZED, MARKED, PETRIFIED, PRONE, RESTRAINED, SLOWED,
	STUNNED, SURPRISED, UNCONSCIOUS, WEAKENED
}
