package com.jimmie.domain.creatures;

public enum Keyword {
	ACID, AIR, AQUATIC, BLIND, CHARM, COLD, CONSTRUCT, DEMON, DEVIL, DISEASE, DRAGON, EARTH,
	FEAR, FIRE, FORCE, GAZE, GIANT, HEALING, HOMUNCULUS, ILLUSION, IMPLEMENT, LIGHTNING,
	LIVING_CONSTRUCT, MOUNT, NECROTIC, OOZE, PLANT, POISON, POLYMORPH, PSYCHIC, RADIANT,
	REPTILE, SHAPE_CHANGER, SPIDER, SWARM, TELEPORTATION, THUNDER, UNDEAD, WATER, WEAPON, ZONE
}
