package com.jimmie.domain.items.weapons;

public enum WeaponType {
	CLUB, DAGGER, JAVELIN, MACE, SICKLE, SPEAR, GREATCLUB, MORNINGSTAR, QUARTERSTAFF, SCYTHE, BATTLEAXE, FLAIL, HANDAXE,
	LONGSWORD, SCIMITAR, SHORTSWORD, THROWING_HAMMER, WARHAMMER, WAR_PICK, FALCHION, GLAIVE, GREATAXE, GREATSWORD,
	HALBERD, HEAVY_FLAIL, LONGSPEAR, MAUL, BASTARD_SWORD, KATAR, RAPIER, SPIKED_CHAIN, ANY, UNARMED_ATTACK,
	HAND_CROSSBOW, SLING, LONGBOW, SHORTBOW, SHURIKEN
}
