package com.jimmie.domain.items.weapons;

public enum WeaponCategory {
	SIMPLE_MELEE, MILITARY_MELEE, SUPERIOR_MELEE, IMPROVISED_MELEE, SIMPLE_RANGED, MILITARY_RANGED, SUPERIOR_RANGED, IMPROVISED_RANGED
}
