package com.jimmie.domain;

public enum AttackType {
	MELEE_WEAPON, MELEE_1, MELEE_TOUCH, RANGED_WEAPON, RANGED_NUMBER, RANGED_SIGHT, CLOSE_BURST, CLOSE_BLAST, AREA_BURST, AREA_WALL, PERSONAL, NONE, MELEE_OR_RANGED_WEAPON
}
