package com.jimmie.domain;

public enum DiceRollType {
	ATTACK_ROLL_MODIFICATION, ABILITY_SCORE_ROLL, INITIATIVE_ROLL, SKILL_CHECK_ROLL, SAVING_THROW_ROLL, ATTACK_ROLL, DAMAGE_ROLL_MODIFICATION, HIT_POINT_MODIFICATION,
	SAVING_THROW_ROLL_MODIFICATION, SKILL_CHECK_ROLL_MODIFICATION, DAMAGE_ROLL, WILD_SOUL

}
