package com.jimmie.domain;

public enum EffectType {
	CHARM, CONJURATION, FEAR, HEALING, ILLUSION, POISON, POLYMORPH, RELIABLE, SLEEP, STANCE, TELEPORTATION, ZONE,
	NONE, RAGE, BEAST_FORM, SUMMONING, SPIRIT, BEAST, INVIGORATING, RATTLING, AUGMENTABLE, FULL_DISCIPLINE, RUNIC
}
