package com.jimmie.domain;

public enum EffecteeType {
	ALL_CREATURES, ENEMIES, ALLIES, BLINDED_TARGET, DAZED_TARGET,
	DEAFENED_TARGET, DOMINATED_TARGET, DYING_TARGET, HELPLESS_TARGET,
	IMMOBILIZED_TARGET, MARKED_TARGET, PETRIFIED_TARGET, PRONE_TARGET,
	RESTRAINED_TARGET, SLOWED_TARGET, STUNNED_TARGET, SURPRISED_TARGET,
	UNCONSCIOUS_TARGET, WEAKENED_TARGET
}
