package com.jimmie.domain;

public enum PowerId {
	BOND_OF_PURSUIT, RADIANT_VENGEANCE, ANGELIC_ALACRITY, ASPECT_OF_MIGHT, MISDIRECTED_MARK, VISCIOUS_MOCKERY, BLUNDER, STIRRING_SHOUT, BASIC_MELEE_ATTACK, AID_ANOTHER,
	SURE_STRIKE, TIDE_OF_IRON, COVERING_ATTACK, SECOND_WIND, SPEND_ACTION_POINT, FORCEFUL_PUSH, FORCE_PUSH, KINETIC_TRAWL, MEMORY_HOLE, TELEKINETIC_ANCHOR, COMEBACK_STRIKE,
	EARTH_SHIELD_STRIKE, THUNDER_RAM_ASSAULT, STRENGTH_OF_STONE, SPEAR, SHIFTY, SHORT_SWORD, OATH_OF_ENMITY, MAJESTIC_WORD, JAVELIN, DAGGER, SLING,
	FORM_OF_THE_WILLOW_SENTINEL

}
