package com.jimmie.domain;

public enum SkillType {
	ACROBATICS, ARCANA, ATHLETICS, BLUFF, DIPLOMACY, DUNGEONEERING, ENDURANCE, HEAL, HISTORY, INSIGHT, INTIMIDATE,
	NATURE, PERCEPTION, RELIGION, STEALTH, STREETWISE, THIEVERY
}
