package com.jimmie.domain;

public enum TemporaryEffectType {
	REF_MOD, WILL_MOD, AC_MOD, DMG_MOD, FORT_MOD, ATCK_ROLL_MOD, RCV_DMG_MOD, SPEED_MOD, CALL_OF_THE_BEAST_EFFECT, AID_ANOTHER_BONUS, DMG_RESIST, ONGOING_DMG,
	INVISIBILITY
}
