package com.jimmie.domain;

public enum TemporaryEffectReason {
	DEFIANT_WORD, BLUNDER, DIVINE_STRENGTH, DIVINE_CHALLENGE, RUNE_OF_DESTRUCTION, EARTH_SHIELD_STRIKE, ENFEEBLING_STRIKE, RADIANT_DELIRIUM, RUNE_OF_MENDING,
	SECOND_WIND, SHIELDING_SMITE, TIDE_OF_IRON, VICIOUS_MOCKERY, WORD_OF_BINDING, WORD_OF_EXCHANGE, CHAOS_BURST, DAZZLING_RAY, RAZORCLAW_SHIFTING, CALL_OF_THE_BEAST, 
	AID_ANOTHER, STONES_ENDURANCE, WILD_MAGIC, FIRES_OF_LIFE

}
