package com.jimmie.domain;

public enum TemporaryEffectType {
	REFLEX_MODIFIER, WILL_MODIFIER, ARMOR_CLASS_MODIFIER, DAMAGE_MODIFIER, FORTITUDE_MODIFIER, ATTACK_ROLL_MODIFIER, RECEIVING_DAMAGE_MODIFIER, SPEED_MODIFIER,
	CALL_OF_THE_BEAST_EFFECT, AID_ANOTHER_BONUS, DAMAGE_RESISTANCE, ONGOING_DAMAGE
}
