package com.jimmie.domain;

public enum TimeConstraint {
	ALWAYS, NEVER, START_OF_MY_TURN, END_OF_MY_TURN,
	START_OF_ANY_TURN, END_OF_ANY_TURN,
	START_OF_AN_ENEMIES_TURN, END_OF_AN_ENEMIES_TURN,
	START_OF_AN_ALLIES_TURN, END_OF_AN_ALLIES_TURN
}
