package com.jimmie.domain;

public enum TimeType {
	SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS, DECADES, CENTURIES, EONS, ETERNITY, SPECIAL, UNTIL_DISCHARGED, PERMANENT,
	INSTANTANEOUS, UNTIL_DISMISSED, UNTIL_BROKEN
}
