package com.jimmie.domain.items;

public enum GearType {
	STANDARD_ADVENTURERS_KIT, BACKPACK, BEDROLL, FLINT_AND_STEEL, BELT_POUCH, TRAIL_RATIONS, HEMPEN_ROPE, SUNRODS, WATERSKIN, ARROWS, CROSSBOW_BOLTS,
	SLING_BULLETS, ORB, ROD, STAFF, WAND, CANDLE, CHAIN, CHEST, CLIMBERS_KIT, GRAPPLING_HOOK, HAMMER, PITONS, EVERBURNING_TORCH, FINE_CLOTHING, FLASK, HOLY_SYMBOL,
	JOURNEYBREAD, LANTERN, RITUAL_BOOK, SILK_ROPE, SPELLBOOK, TENT, THIEVES_TOOLS, TORCH, POTION_OF_HEALING

}
