package com.jimmie.encounters;

import java.util.ArrayList;

import com.jimmie.domain.Position;
import com.jimmie.domain.creatures.monsters.KoboldDragonshield;
import com.jimmie.domain.creatures.monsters.KoboldSkirmisher;
import com.jimmie.domain.creatures.monsters.KoboldWyrmpriest;
import com.jimmie.util.Utils;
import com.jimmie.domain.creatures.Character;
import com.jimmie.domain.creatures.monsters.Monster;
import com.jimmie.domain.map.LocationType;
import com.jimmie.domain.map.Map;
import com.jimmie.domain.map.MapLocation;

public class KoboldAmbushEncounter extends Encounter {

	public KoboldAmbushEncounter() {
		/* Set up the monsters */
		KoboldSkirmisher k = new KoboldSkirmisher();
		k.setName("Kobold Skirmisher");
		k.setDisplayName("K");
		k.setCurrentPosition(new Position(14,18));
		KoboldDragonshield d1 = new KoboldDragonshield();
		d1.setName("Kobold Dragonshield 1");
		d1.setDisplayName("D1");
		d1.setCurrentPosition(new Position(15,17));
		KoboldDragonshield d2 = new KoboldDragonshield();
		d2.setName("Kobold Dragonshield 2");
		d2.setDisplayName("D2");
		d2.setCurrentPosition(new Position(19,10));
		KoboldDragonshield d3 = new KoboldDragonshield();
		d3.setName("Kobold Dragonshield 3");
		d3.setDisplayName("D3");
		d3.setCurrentPosition(new Position(18,10));
		KoboldWyrmpriest w = new KoboldWyrmpriest();
		w.setName("Kobold Wyrmpriest");
		w.setDisplayName("W");
		w.setCurrentPosition(new Position(15,19));
		monsters = new ArrayList<Monster>();
		monsters.add(k);
		monsters.add(d1);
		monsters.add(d2);
		monsters.add(d3);
		monsters.add(w);
		

		
	
		/* Set up the player characters */
/*		Avenger avenger = new Avenger();
		avenger.addPower(Avenger.BOND_OF_PURSUIT);
		avenger.addPower(Avenger.RADIANT_VENGEANCE);
		avenger.addPower(Avenger.ANGELIC_ALACRITY);
		avenger.addPower(Avenger.OATH_OF_ENMITY);
		avenger.addPower(Avenger.ABJURE_UNDEAD);
		avenger.addPower(Avenger.DIVINE_GUIDANCE);
		avenger.addPower(Avenger.ASPECT_OF_MIGHT);
		avenger.setCensure(Avenger.CENSURE_OF_PURSUIT);
		Elf elf = new Elf();
		PlayerCharacter elfAvenger = new PlayerCharacter(elf, avenger);
		avenger.setOwner(elfAvenger);
		elf.setOwner(elfAvenger);
		elfAvenger.setName("Thokul Moonshadow");
		elfAvenger.setDisplayName("TM");
		elfAvenger.setInitiative(3);
		elfAvenger.setMaxHitPoints(23);
		elfAvenger.setCurrentHitPoints(15);
		elfAvenger.setFortitude(12);
		elfAvenger.setReflex(14);
		elfAvenger.setWill(15);
		elfAvenger.setSpeed(7);
		elfAvenger.setStrength(11);
		elfAvenger.setConstitution(12);
		elfAvenger.setDexterity(16);
		elfAvenger.setIntelligence(13);
		elfAvenger.setWisdom(18);
		elfAvenger.setCharisma(10);
		LongSword ls1 = new LongSword();
		elfAvenger.addWeaponProficiency(ls1.getWeaponId());
		elfAvenger.setReadiedWeapon(ls1);
		elfAvenger.setArmor(new ClothArmor());
		elfAvenger.setReadiedShield(new NoShield());
		elfAvenger.setCurrentPosition(new Position(16,13));
		elfAvenger.setHealingSurgesPerDay(8);
		elfAvenger.setHealingSurgeValue(5);
		elfAvenger.setCurrentSurgeUses(1);
		elfAvenger.setTrainedInAcrobatics(true);
		elfAvenger.setTrainedInPerception(true);
		elfAvenger.setTrainedInReligion(true);
		elfAvenger.setTrainedInStealth(true);
		elfAvenger.setImagePath("c:\\eclipse_workspace\\DungeonsAndDragons\\resources\\ElfAvenger.JPG");
		elfAvenger.initializeForNewDay();
		Utils.saveCharacter(elfAvenger);

		
		
		Bard bard = new Bard();
		bard.addPower(Bard.MISDIRECTED_MARK);
		bard.addPower(Bard.VICIOUS_MOCKERY);
		bard.addPower(Bard.BLUNDER);
		bard.addPower(Bard.MAJESTIC_WORD);
		bard.addPower(Bard.WORDS_OF_FRIENDSHIP);

//      TODO: I am not currently implementing the Ghost Sound power.
//      Also, it should come from the Wizard class, even though this bard is using it.
//      bard.addPower(Wizard.GHOST_SOUND);

		bard.addPower(Bard.STIRRING_SHOUT);
		Gnome gnome = new Gnome();
		gnome.addPower(Gnome.FADE_AWAY);
		
		PlayerCharacter kellen = new PlayerCharacter(gnome, bard);
		bard.setOwner(kellen);
		gnome.setOwner(kellen);
		kellen.setName("Kellen Wordsmith");
		kellen.setDisplayName("KW");
		kellen.setInitiative(1);
		kellen.setMaxHitPoints(25);
		kellen.setCurrentHitPoints(21);
		kellen.setFortitude(11);
		kellen.setReflex(15);
		kellen.setWill(15);
		kellen.setSpeed(4);
		kellen.setStrength(10);
		kellen.setConstitution(13);
		kellen.setDexterity(12);
		kellen.setIntelligence(16);
		kellen.setWisdom(11);
		kellen.setCharisma(18);
		kellen.setCurrentPosition(new Position(19,14));
		kellen.setReadiedWeapon(new ShortSword());
		kellen.setReadiedShield(new LightShield());
		kellen.setArmor(new ChainMail());
		kellen.setHealingSurgesPerDay(8);
		kellen.setHealingSurgeValue(6);
		kellen.setTrainedInArcana(true);
		kellen.setTrainedInBluff(true);
		kellen.setTrainedInIntimidate(true);
		kellen.setTrainedInPerception(true);
		kellen.setTrainedInStreetwise(true);
		kellen.setImagePath("c:\\eclipse_workspace\\DungeonsAndDragons\\resources\\GnomeBard.JPG");
		kellen.initializeForNewDay();
		Utils.saveCharacter(kellen);
		
		Warden warden = new Warden();
		warden.addPower(Warden.STRENGTH_OF_STONE);
		warden.addPower(Warden.EARTH_SHIELD_STRIKE);
		warden.addPower(Warden.WARDENS_FURY);
		warden.addPower(Warden.THUNDER_RAM_ASSAULT);
		warden.addPower(Warden.WARDENS_GRASP);
		warden.addPower(Warden.FORM_OF_THE_WILLOW_SENTINEL);
		warden.addOption(Warden.EARTH_STRENGTH);
		Goliath goliath = new Goliath();
		goliath.addPower(Goliath.STONES_ENDURANCE);
		PlayerCharacter glock = new PlayerCharacter(goliath, warden);
		warden.setOwner(glock);
		goliath.setOwner(glock);
		glock.setName("Glock Elmhurst");
		glock.setDisplayName("GE");
		glock.setInitiative(1);
		glock.setMaxHitPoints(33);
		glock.setCurrentHitPoints(16);
		glock.setFortitude(15);
		glock.setReflex(11);
		glock.setWill(13);
		glock.setSpeed(6);
		glock.setStrength(18);
		glock.setConstitution(16);
		glock.setDexterity(12);
		glock.setIntelligence(11);
		glock.setWisdom(10);
		glock.setCharisma(13);
		glock.setCurrentPosition(new Position(15,14));
		WarHammer warHammer = new WarHammer();
		glock.setReadiedWeapon(warHammer);
		glock.addWeaponProficiency(warHammer.getWeaponId());
		glock.setReadiedShield(new LightShield());
		glock.setArmor(new HideArmor());
		glock.setHealingSurgesPerDay(12);
		glock.setCurrentSurgeUses(1);
		glock.setHealingSurgeValue(8);
		glock.setTrainedInAthletics(true);
		glock.setTrainedInHeal(true);
		glock.setTrainedInNature(true);
		glock.setTrainedInPerception(true);
		glock.setImagePath("c:\\eclipse_workspace\\DungeonsAndDragons\\resources\\GoliathWarden.JPG");
		glock.initializeForNewDay();
		Utils.saveCharacter(glock);

		Fighter fighter = new Fighter();
		fighter.addPower(Fighter.SURE_STRIKE);
		fighter.addPower(Fighter.TIDE_OF_IRON);
		fighter.addPower(Fighter.COVERING_ATTACK);
		fighter.addPower(Fighter.COMEBACK_STRIKE);
		HalfOrc halfOrc = new HalfOrc();
		halfOrc.addPower(HalfOrc.FURIOUS_ASSAULT);
		halfOrc.addPower(HalfOrc.HALF_ORC_RESILIENCE);
		PlayerCharacter halfOrcFighter = new PlayerCharacter(halfOrc, fighter);
		fighter.setOwner(halfOrcFighter);
		fighter.setFighterWeaponTalent(Fighter.ONE_HANDED_WEAPON);
		halfOrc.setOwner(halfOrcFighter);
		halfOrcFighter.setName("Eleak Nightraider");
		halfOrcFighter.setDisplayName("EN");
		//halfOrcFighter.setInitiative(3);
		halfOrcFighter.setInitiative(3);
		halfOrcFighter.setMaxHitPoints(27);
		halfOrcFighter.setCurrentHitPoints(13);
		halfOrcFighter.setFortitude(16);
		halfOrcFighter.setReflex(15);
		halfOrcFighter.setWill(11);
		halfOrcFighter.setSpeed(5);
		halfOrcFighter.setStrength(18);
		halfOrcFighter.setConstitution(12);
		halfOrcFighter.setDexterity(16);
		halfOrcFighter.setIntelligence(10);
		halfOrcFighter.setWisdom(13);
		halfOrcFighter.setCharisma(11);
		LongSword ls = new LongSword();
		halfOrcFighter.setReadiedWeapon(ls);
		halfOrcFighter.setReadiedShield(new HeavyShield());
		halfOrcFighter.addWeaponProficiency(ls.getWeaponId());
		halfOrcFighter.setCurrentPosition(new Position(19,16));
		halfOrcFighter.setArmor(new ScaleArmor());
		halfOrcFighter.setHealingSurgesPerDay(10);
		halfOrcFighter.setHealingSurgeValue(6);
		halfOrcFighter.setTrainedInAthletics(true);
		halfOrcFighter.setTrainedInHeal(true);
		halfOrcFighter.setTrainedInIntimidate(true);
		halfOrcFighter.setImagePath("c:\\eclipse_workspace\\DungeonsAndDragons\\resources\\HalfOrcFighter.JPG");
		halfOrcFighter.initializeForNewDay();
		Utils.saveCharacter(halfOrcFighter);

		Human human = new Human();
		Psion psion = new Psion();
		psion.addPower(Psion.KINETIC_TRAWL);
		psion.addPower(Psion.FORCE_PUNCH);
		psion.addPower(Psion.MEMORY_HOLE);
		psion.addPower(Psion.FAR_HAND);
		psion.addPower(Psion.FORCEFUL_PUSH);
		psion.addPower(Psion.TELEKINETIC_ANCHOR);
		PlayerCharacter zanros = new PlayerCharacter(human, psion);
		psion.setOwner(zanros);
		human.setOwner(zanros);
		zanros.setName("Zanros Hawklight");
		zanros.setDisplayName("ZH");
		zanros.setInitiative(0); 
		zanros.setMaxHitPoints(25);
		zanros.setCurrentHitPoints(25);
		zanros.setFortitude(12);
		zanros.setReflex(15);
		zanros.setWill(15);
		zanros.setSpeed(6);
		zanros.setStrength(12);
		zanros.setConstitution(13);
		zanros.setDexterity(10);
		zanros.setIntelligence(18);
		zanros.setWisdom(14);
		zanros.setCharisma(11);
		zanros.setReadiedWeapon(new Mace());
		zanros.setReadiedShield(new NoShield());
		zanros.setCurrentPosition(new Position(17,15));
		zanros.setArmor(new ClothArmor());
		zanros.setHealingSurgesPerDay(7);
		zanros.setHealingSurgeValue(6);
		zanros.setTrainedInArcana(true);
		zanros.setTrainedInDungeoneering(true);
		zanros.setTrainedInInsight(true);
		zanros.setTrainedInIntimidate(true);
		zanros.setTrainedInPerception(true);
		zanros.setImagePath("c:\\eclipse_workspace\\DungeonsAndDragons\\resources\\HumanPsion.JPG");
		zanros.initializeForNewDay();
		Utils.saveCharacter(zanros);
*/		
		Character elfAvenger = Utils.loadCharacter("Thokul Moonshadow");
		Character kellen = Utils.loadCharacter("Kellen Wordsmith");
		Character glock = Utils.loadCharacter("Glock Elmhurst");
		Character halfOrcFighter = Utils.loadCharacter("Eleak Nightraider");
		Character zanros = Utils.loadCharacter("Zanros Hawklight");
		
		characters = new ArrayList<Character>();
		characters.add(elfAvenger);
		characters.add(kellen);
		characters.add(glock);
		characters.add(halfOrcFighter);
		characters.add(zanros);
		

		map = new Map();
		map.setWidth(30);
		map.setHeight(21);
		map.addLocation(new MapLocation(new Position(1,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,6), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(1,7), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(1,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(1,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(2,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,6), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(2,7), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(2,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(2,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(3,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,7), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(3,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(3,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(3,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(3,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(4,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,7), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(4,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(4,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(4,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(4,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,13), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(4,14), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(4,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(4,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(4,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(4,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(5,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,2), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(5,3), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(5,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(5,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(5,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(5,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(5,13), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(5,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(5,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(5,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(5,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(6,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,2), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(6,3), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(6,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(6,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(6,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(6,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(6,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(6,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(6,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(6,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(7,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,7), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(7,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(7,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(7,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(7,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(7,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(7,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(7,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(8,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,6), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(8,7), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(8,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(8,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(8,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(8,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(8,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,16), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(8,17), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(8,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(8,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(9,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(9,5), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(9,6), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(9,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(9,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(9,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(9,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(9,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,16), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(9,17), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(9,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(10,5), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(10,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,9), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(10,10), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(10,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(10,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(10,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(10,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(10,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,9), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(11,10), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(11,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(11,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(11,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(11,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(11,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(12,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(12,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(12,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(13,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(13,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(13,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(13,16), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(13,17), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(13,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(14,2), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(14,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(14,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(14,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(14,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(14,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(14,16), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(14,17), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(14,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(15,1), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(15,2), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(15,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(15,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(15,5), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(15,6), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(15,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,12), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(15,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(15,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(15,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(15,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(15,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,1), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(16,2), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(16,3), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(16,4), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(16,5), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(16,6), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,7), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,8), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(16,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(16,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(16,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(16,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(16,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(16,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(16,16), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,17), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(16,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(16,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(16,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,1), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(17,2), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(17,3), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(17,4), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(17,5), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,6), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,7), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,8), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(17,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(17,11), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(17,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(17,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(17,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(17,17), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(17,21), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(18,1), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(18,2), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(18,3), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(18,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(18,5), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(18,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(18,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(18,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(18,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(18,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(18,11), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(18,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(18,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(18,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(18,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(18,16), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(18,17), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(18,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(18,19), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(18,20), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(18,21), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(19,1), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(19,2), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(19,3), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(19,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(19,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(19,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(19,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(19,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(19,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(19,11), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,13), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(19,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(19,16), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(19,17), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,18), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(19,20), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(19,21), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(20,1), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(20,2), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(20,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(20,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(20,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(20,8), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,9), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,10), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,11), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,13), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(20,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(20,16), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(20,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(20,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(20,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(20,21), LocationType.WALL));
		map.addLocation(new MapLocation(new Position(21,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,2), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,9), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,10), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,11), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(21,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(21,16), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(21,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(21,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(21,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,2), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,10), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,11), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,12), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(22,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(22,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(22,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(22,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(22,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(23,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(23,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,4), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(23,5), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(23,6), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(23,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,11), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(23,12), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(23,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(23,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(23,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(23,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(23,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(24,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,11), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(24,12), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(24,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(24,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(24,15), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(24,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(24,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(25,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(25,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(25,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(25,15), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(25,16), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(25,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(25,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(26,2), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(26,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(26,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(26,13), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(26,14), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(26,15), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(26,16), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(26,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(26,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(27,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(27,2), LocationType.FOLIAGE));		
		map.addLocation(new MapLocation(new Position(27,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(27,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,7), LocationType.BOULDER));
		map.addLocation(new MapLocation(new Position(27,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(27,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(27,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(27,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,14), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(27,15), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(27,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(27,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(28,1), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(28,2), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(28,3), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(28,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(28,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(28,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(28,12), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(28,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(28,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(28,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(29,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(29,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(29,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(29,11), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(29,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(29,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(29,21), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(30,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,6), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,8), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(30,9), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(30,10), LocationType.ROAD));
		map.addLocation(new MapLocation(new Position(30,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(30,19), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(30,20), LocationType.FOLIAGE));
		map.addLocation(new MapLocation(new Position(30,21), LocationType.FOLIAGE));		
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
}
