package com.jimmie.encounters;

import java.util.ArrayList;

import com.jimmie.domain.Position;
import com.jimmie.domain.creatures.monsters.KoboldDragonshield;
import com.jimmie.domain.creatures.monsters.KoboldMinion;
import com.jimmie.domain.creatures.monsters.KoboldSkirmisher;
import com.jimmie.domain.creatures.monsters.KoboldSlinger;
import com.jimmie.domain.creatures.monsters.Monster;
import com.jimmie.domain.creatures.Character;
import com.jimmie.domain.map.LocationType;
import com.jimmie.domain.map.Map;
import com.jimmie.domain.map.MapLocation;
import com.jimmie.util.Utils;

public class KoboldLairOutsideEncounter extends Encounter {
	public KoboldLairOutsideEncounter() {
		/* Set up the monsters */
		KoboldMinion m1 = new KoboldMinion();
		m1.setName("Kobold Minion 1");
		m1.setDisplayName("M1");
		m1.setCurrentPosition(new Position(4,4));
		KoboldMinion m2 = new KoboldMinion();
		m2.setName("Kobold Minion 2");
		m2.setDisplayName("M2");
		m2.setCurrentPosition(new Position(5,3));
		KoboldMinion m3 = new KoboldMinion();
		m3.setName("Kobold Minion 3");
		m3.setDisplayName("M3");
		m3.setCurrentPosition(new Position(6,6));
		KoboldMinion m4 = new KoboldMinion();
		m4.setName("Kobold Minion 4");
		m4.setDisplayName("M4");
		m4.setCurrentPosition(new Position(7,3));
		KoboldMinion m5 = new KoboldMinion();
		m5.setName("Kobold Minion 5");
		m5.setDisplayName("M5");
		m5.setCurrentPosition(new Position(8,7));
		KoboldMinion m6 = new KoboldMinion();
		m6.setName("Kobold Minion 6");
		m6.setDisplayName("M6");
		m6.setCurrentPosition(new Position(9,11));
		KoboldMinion m7 = new KoboldMinion();
		m7.setName("Kobold Minion 7");
		m7.setDisplayName("M7");
		m7.setCurrentPosition(new Position(11,13));
		KoboldMinion m8 = new KoboldMinion();
		m8.setName("Kobold Minion 8");
		m8.setDisplayName("M8");
		m8.setCurrentPosition(new Position(13,7));
		KoboldMinion m9 = new KoboldMinion();
		m9.setName("Kobold Minion 9");
		m9.setDisplayName("M9");
		m9.setCurrentPosition(new Position(13,9));
		KoboldMinion m10 = new KoboldMinion();
		m10.setName("Kobold Minion 10");
		m10.setDisplayName("M10");
		m10.setCurrentPosition(new Position(14,13));
			
		KoboldSkirmisher k = new KoboldSkirmisher();
		k.setName("Kobold Skirmisher");
		k.setDisplayName("K");
		k.setCurrentPosition(new Position(15,19));
		
		KoboldDragonshield d = new KoboldDragonshield();
		d.setName("Kobold Dragonshield");
		d.setDisplayName("D");
		d.setCurrentPosition(new Position(7,11));
		
		KoboldSlinger s = new KoboldSlinger();
		s.setName("Kobold Slinger");
		s.setDisplayName("S");
		s.setCurrentPosition(new Position(14,15));
		monsters = new ArrayList<Monster>();		
		
		monsters.add(m1);		
		monsters.add(m2);		
		monsters.add(m3);		
		monsters.add(m4);		
		monsters.add(m5);		
		monsters.add(m6);		
		monsters.add(m7);		
		monsters.add(m8);		
		monsters.add(m9);		
		monsters.add(m10);
		monsters.add(k);
		monsters.add(d);
		monsters.add(s);

		
	
		/* Set up the player characters */
		Character elfAvenger = Utils.loadCharacter("Jim");
		elfAvenger.setCurrentPosition(new Position(3,19));
		Character kellen = Utils.loadCharacter("Jim");
		kellen.setCurrentPosition(new Position(1,21));
		Character glock = Utils.loadCharacter("Jim");
		glock.setCurrentPosition(new Position(1,19));
		Character halfOrcFighter = Utils.loadCharacter("Jim");
		halfOrcFighter.setCurrentPosition(new Position(3,18));
		Character zanros = Utils.loadCharacter("Jim");
		zanros.setCurrentPosition(new Position(2,20));
		
		characters = new ArrayList<Character>();
		characters.add(elfAvenger);
		characters.add(kellen);
		characters.add(glock);
		characters.add(halfOrcFighter);
		characters.add(zanros);
		
		map = new Map();
		map.setWidth(15);
		map.setHeight(21);
		map.addLocation(new MapLocation(new Position(1,1), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(1,2), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(1,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,4), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(1,5), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(1,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(1,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(1,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(1,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,1), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(2,2), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(2,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,4), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(2,5), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(2,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(2,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(2,8), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(2,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(2,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,1), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(3,2), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(3,3), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(3,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,5), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(3,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(3,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(3,8), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(3,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,10), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,12), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(3,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(3,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,2), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(4,3), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(4,4), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(4,5), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(4,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,8), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,9), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,10), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,11), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,12), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,13), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,14), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(4,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(4,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,1), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,3), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(5,4), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(5,5), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(5,6), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(5,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,8), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,9), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,10), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,11), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,12), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,13), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,14), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(5,20), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(5,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,1), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,5), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(6,6), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(6,7), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(6,8), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(6,9), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,10), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(6,11), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(6,12), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(6,13), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,14), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,15), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(6,20), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(6,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,1), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,4), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,5), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,6), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(7,7), LocationType.DEEP_RIVER));
		map.addLocation(new MapLocation(new Position(7,8), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(7,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,10), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(7,11), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(7,12), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(7,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,14), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,15), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,16), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(7,20), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(7,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,1), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,4), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,5), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,8), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(8,9), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(8,10), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(8,11), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(8,12), LocationType.SACRED_CIRCLE));
		map.addLocation(new MapLocation(new Position(8,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,15), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,16), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,17), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(8,20), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(8,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(9,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(9,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,9), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(9,10), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(9,11), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,12), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(9,13), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(9,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,15), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(9,16), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(9,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(9,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(9,20), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(9,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(10,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(10,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(10,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,9), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(10,10), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(10,11), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(10,12), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(10,13), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(10,14), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(10,15), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(10,16), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(10,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(10,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(10,21), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,2), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,3), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,7), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,8), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,10), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(11,11), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(11,12), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(11,13), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(11,14), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(11,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,16), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,18), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(11,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(11,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,2), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(12,3), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(12,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(12,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,10), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(12,11), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(12,12), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(12,13), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(12,14), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(12,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(12,18), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(12,19), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(12,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(12,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,2), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(13,3), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(13,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(13,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,10), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(13,11), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(13,12), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(13,13), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(13,14), LocationType.FALLEN_TREE));
		map.addLocation(new MapLocation(new Position(13,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(13,18), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(13,19), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(13,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(13,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,1), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,2), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,3), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(14,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,9), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,10), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(14,11), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(14,12), LocationType.SHALLOW_RIVER));
		map.addLocation(new MapLocation(new Position(14,13), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(14,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(14,21), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,1), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(15,2), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(15,3), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(15,4), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,5), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,6), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(15,7), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,8), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,9), LocationType.WATERFALL));
		map.addLocation(new MapLocation(new Position(15,10), LocationType.WATERFALL));
		map.addLocation(new MapLocation(new Position(15,11), LocationType.WATERFALL));
		map.addLocation(new MapLocation(new Position(15,12), LocationType.WATERFALL));
		map.addLocation(new MapLocation(new Position(15,13), LocationType.WATERFALL));
		map.addLocation(new MapLocation(new Position(15,14), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,15), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,16), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,17), LocationType.TREE));
		map.addLocation(new MapLocation(new Position(15,18), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,19), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,20), LocationType.GRASS));
		map.addLocation(new MapLocation(new Position(15,21), LocationType.GRASS));
	}
}
