package com.jimmie.domain.items.armor;

public enum ArmorType {
	CLOTH, FEYWEAVE, STARWEAVE, LEATHER, FEYLEATHER, STARLEATHER, HIDE, DARKHIDE, ELDERHIDE, CHAINMAIL,
	FORGEMAIL, SPIRITMAIL, SCALE, WWYRMSCALE, ELDERSCALE, PLATE, WARPLATE, GODPLATE, LIGHT_SHIELD, HEAVY_SHIELD
}
